version: '3'
volumes:
    postgres_data:

services:
    nginx:
        image: nginx:latest
        ports:
          - 1337:80
        volumes:
            - ./webnotes/static:/src/articles/static
            - .:/etc/nginx/conf.d
            - ./webnotes/media:/src/articles/media
            - ./webnotes/logs:/src/articles/logs
        depends_on:
            - web
        networks:
            - my-net
    web:
        build:
            context: .
        volumes:
            - .:/src/articles
            - ./webnotes/static:/src/articles/webnotes/static
        ports:
            - 8000:8000
        depends_on:
            - db
        env_file:
            -   .env
        entrypoint: ["bash", "docker-entrypoint.sh"]
        networks:
            - my-net
    db:
        image: postgres:9.3.22
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            -   .env
        networks:
            - my-net
networks:
  my-net:
    driver: bridge