# Generated by Django 3.2.7 on 2021-10-22 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='тема')),
                ('text', models.TextField(verbose_name='текст')),
                ('date', models.DateTimeField(verbose_name='дата')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150, verbose_name='автор')),
                ('text', models.CharField(max_length=500, verbose_name='текст')),
                ('date', models.DateTimeField(verbose_name='дата')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newnotes.article')),

            ],
        ),
        migrations.CreateModel(
            name='ArticleUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watched', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newnotes.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('includes_article', models.ManyToManyField(through='newnotes.ArticleCategoryRelation', to='newnotes.Article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newnotes.article')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newnotes.category')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='readers',
            field=models.ManyToManyField(related_name='my_articles', through='newnotes.BookUserRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
