# Generated by Django 3.2.7 on 2021-10-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newnotes', '0002_comment_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
    ]
