# Generated by Django 3.2.7 on 2021-10-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newnotes', '0007_auto_20211028_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
