# Generated by Django 3.2.7 on 2021-10-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newnotes', '0008_remove_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='includes_article',
            field=models.ManyToManyField(through='newnotes.ArticleCategoryRelation', to='newnotes.Article'),
        ),
    ]
